JobApi/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('job/', include('job.urls'), name='job'),
    path('job-app/', include('frontend.urls'), name='jobfrontend'),
]

frontend/urls.py
from django.urls import path
from frontend.views import *


app_name = 'jobfrontend'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    # path('', home, name='home'),
]

job/urls.py
from django.urls import path, include
from rest_framework import routers
from job import views


app_name = 'job'

router = routers.DefaultRouter()
router.register('view-all-job', views.AllJobViewSet, basename='viewalljob')
router.register('view-all-job-applications', views.AllJobApplicationsViewSet, basename='viewalljobapplications')
router.register('view-post-job-user', views.JobRecruiterViewSet, basename='viewpostjobuser')  # FOR  JOB RECRUITERS
router.register('view-hire-job-applications', views.ViewHireUserViewSet, basename='viewhirejobapplications')# FOR  JOB RECRUITERS
router.register('apply-save-job', views.JobSeekerViewSet, basename='applysavejob')  # FOR  JOB SEEKERS
router.register('view-applied-job', views.UserAppliedJobViewSet, basename='viewappliedjob')  # FOR JOB SEEKERS
router.register('view-saved-job', views.UserSavedJobViewSet, basename='viewsavedjob')  # FOR JOB SEEKERS
router.register('edit-view-job-detail', views.JobDetailedViewSet, basename='editviewjobdetail')  # FOR BOTH


urlpatterns = [
    path('', include(router.urls)),
    path('job-application/<int:id>', views.ViewJobApplicationAPI.as_view(), name='jobapplication'),
    path('job-application-update/<int:id>', views.UpdateJobApplicationAPI.as_view(), name='jobapplicationupdate'),
]

frontend/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models

# Create your models here.


INDUSTRY = (
    ("Accountancy", "Accountancy"),
    ("Business", "Business"),
    ("Charity and Voluntary Work", "Charity and Voluntary Work"),
    ("Creative Arts and Design", "Creative Arts and Design"),
    ("Energy and Utilities", "Energy and Utilities"),
    ("Creative Arts and Design", "Creative Arts and Design"),
    ("Engineering and Manufacturing", "Engineering and Manufacturing"),
    ("Environment and Agriculture", "Environment and Agriculture"),
    ("Healthcare", "Healthcare"),
    ("Hospitality and Event Management", "Hospitality and Event Management"),
    ("Information Technology", "Information Technology"),
    ("Law", "Law"),
    ("Leisure, Sports, and Tourism", "Leisure, Sports, and Tourism"),
    ("Marketing, Advertising, and PR", "Marketing, Advertising, and PR"),
    ("Media and Internet", "Media and Internet"),
    ("Property and Consultation", "Property and Consultation"),
    ("Public Services and Administration", "Public Services and Administration"),
    ("Recruitment and HR", "Recruitment and HR"),
    ("Retail", "Retail"),
    ("Sales", "Sales"),
    ("Science and Pharmaceuticals", "Science and Pharmaceuticals"),
    ("Social Care", "Social Care"),
    ("Teacher Training and Education", "Teacher Training and Education"),
    ("Transport and Logistics", "Transport and Logistics"),
)

STATUS = (
    ("Applied", "Applied"),
    ("Selected", "Selected"),
    ("Not Selected", "Not Selected"),
    ("Shortlisted", "Shortlisted"),
)


class JobRecruiter(models.Model):
    user = models.ForeignKey('core.User', on_delete=models.PROTECT)
    company_name = models.CharField(max_length=80)
    job_title = models.CharField(max_length=80)
    location = models.CharField(max_length=50)
    your_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=12)
    industry = models.CharField(max_length=80, choices=INDUSTRY)
    experience = models.CharField(max_length=20)
    salary_from = models.CharField(max_length=20)
    salary_to = models.CharField(max_length=20)
    date = models.DateField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    description = models.TextField()
    requirements = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.job_title)


class JobSeeker(models.Model):
    user = models.ForeignKey('core.User', on_delete=models.PROTECT)
    resume = models.FileField(upload_to="Job/Resume/")
    job = models.ForeignKey('job.JobRecruiter', on_delete=models.PROTECT)
    date = models.DateField(auto_now_add=True)
    saved = models.BooleanField(default=False)
    applied = models.BooleanField(default=False)
    status = models.CharField(max_length=50, choices=STATUS, default="Applied")

    def __str__(self):
        return str(self.user)

frontend/views.py
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponse
# from django.views.generic import TemplateView
from django.views import View
import requests

# Create your views here.


class HomeView(View):

    def get(self, request):
    
    	response = requests.get("https://nischay-herbal.herokuapp.com/job/view-all-job/")
    	jobdata = response.json()
    	# print(jobdata)
    	context = {'jobdata': jobdata}
    	return render(request, 'job/home.html', context)

class LoginView(View):

    def get(self, request):
        return render(request, 'job/login.html')        

job/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from rest_framework import viewsets, permissions, generics
from rest_framework.views import exception_handler
from rest_framework.response import Response
from .serializers import *
from core.models import User
from job.models import *
from core.permissions import SubscribedUser, IsOwner
from .filter import *
from rest_framework.filters import SearchFilter
from django_filters.rest_framework import DjangoFilterBackend
from django.db import IntegrityError

# Create your views here.


class AllJobViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobRecruiter.objects.all()
    serializer_class = AllJobsSerializer
    permission_classes = [permissions.IsAuthenticated, SubscribedUser]
    filter_backends = (DjangoFilterBackend,)
    filterset_class = CategoriesFilter

    def list(self, request, *args, **kwargs):
        queryset = self.queryset.filter(approved=True).order_by('date')
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)


class JobDetailedViewSet(viewsets.ModelViewSet):
    queryset = JobRecruiter.objects.all()
    serializer_class = JobDetailSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner, SubscribedUser]


class JobRecruiterViewSet(viewsets.ModelViewSet):
    queryset = JobRecruiter.objects.all()
    serializer_class = JobRecruiterSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwner, SubscribedUser]

    def list(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "User Does not exist"}, status=400)

        queryset = self.queryset.filter(user=user).order_by('-date')
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def perform_create(self, serializer, *args, **kwargs):
        serializer.save(user=self.request.user)


class JobSeekerViewSet(viewsets.ModelViewSet):
    queryset = JobSeeker.objects.all()
    serializer_class = JobSeekerSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner, SubscribedUser]
    search_fields = ['applied', 'date']
    filter_backends = [SearchFilter, DjangoFilterBackend]
    filterset_class = ViewJobFilter

    def list(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "User Does not exist"}, status=400)
        queryset = self.queryset.filter(user=user).order_by('-date')
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):

        job = JobSeeker.objects.filter(user=self.request.user, job=self.request.data['job'], applied=True)

        # job = JobSeeker.objects.filter(user=self.request.user, job=self.request.data['job'], applied=True, saved=True)
        if job.exists():
            return Response({"error": "Already Applied"}, status=400)
        else:
            serializer = self.get_serializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            self.perform_create(serializer.save(user=self.request.user))
            return Response({"msg": "Successfully Applied"}, status=200)


class UserAppliedJobViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobSeeker.objects.all()
    serializer_class = UserAppliedJobSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner, SubscribedUser]

    def list(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "User Does not exist"}, status=400)
        queryset = self.queryset.filter(user=user, applied=True).order_by('-date')
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)


class UserSavedJobViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobSeeker.objects.all()
    serializer_class = UserAppliedJobSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner, SubscribedUser]

    def list(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "User Does not exist"}, status=400)
        queryset = self.queryset.filter(user=user, applied=False, saved=True).order_by('-date')
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)


class AllJobApplicationsViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobSeeker.objects.all()
    serializer_class = AllJobApplicationsSerializer
    permission_classes = [permissions.IsAuthenticated]


class ViewHireUserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobRecruiter.objects.all()
    serializer_class = ViewHireUserSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner, SubscribedUser]

    def list(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "User Does not exist"}, status=400)
        queryset = self.queryset.filter(user=user)
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)


class ViewJobApplicationAPI(generics.RetrieveAPIView):
    queryset = JobSeeker.objects.all()
    serializer_class = ViewJobApplicationsSerializer
    permission_classes = [permissions.IsAuthenticated, SubscribedUser]
    lookup_field = ['id']

    def retrieve(self, request, *args, **kwargs):
        try:
            job = JobRecruiter.objects.get(id=self.kwargs["id"])
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "Does not exist"}, status=400)
        queryset = self.queryset.filter(job=job)
        queryset = self.filter_queryset(queryset)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data, status=200)


class UpdateJobApplicationAPI(generics.RetrieveUpdateAPIView):
    queryset = JobSeeker.objects.all()
    serializer_class = UpdateJobApplicationSerializer
    permission_classes = [permissions.IsAuthenticated, SubscribedUser]
    lookup_field = ['id']

    def retrieve(self, request, *args, **kwargs):
        try:
            queryset = self.queryset.get(id=self.kwargs["id"])
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST": "Does not exist"}, status=400)

        serializer = self.get_serializer(queryset)
        return Response(serializer.data, status=200)

    def update(self, request, *args, **kwargs):
        try:
            instance = self.queryset.get(id=self.kwargs["id"])
        except ObjectDoesNotExist:
            return Response({"DOES_NOT_EXIST":"Does not exist"}, status=400)
        serializer = self.get_serializer(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=200)

frontend/templates/job/home.html
{% extends 'job/main.html' %}
{% load static %}
{% block title %}AI JOBS{% endblock %}

{% block content %}
<br>



<div class="jumbotron" style="background: rgb(222,220,11);background: linear-gradient(90deg, rgba(222,220,11,1) 0%, rgba(128,228,85,1) 50%, rgba(245,137,154,1) 100%);">
	
	<h1 style="color: #2F4F4F;text-align: center;">Welcome To AI Jobs</h1>      
	<p style="color: #2F4F4F;text-align: center;">Start your carrer with most trusted site.</p>
</div>


<br>

<div class="container">

	{% for job in jobdata %}
	<div class="card">
  		<div class="card-header">
    		Date: {{ job.date}}
  		</div>
  		<div class="card-body">
  			
    		<h5 class="card-title">{{ job.job_title }}</h5>
    		<a href="" style="color:black">
    		<h6>Location : {{ job.location }}</h6>
    		<h6>Salary : {{ job.salary_from }} To {{ job.salary_to }}</h6>
    		<h6>Exp : {{ job.experience }}</h6>

    		<p class="card-text">Requirements : {{ job.requirements}}</p>
    		<br>
    		<a href="#" class="btn btn-primary">View Job</a>
    		<a href="#" class="btn btn-primary">Apply Job</a>
    		</a>
  		</div>
	</div>
	<br>
	{% endfor %}
</div>

<!-- Footer -->
<footer class="page-footer font-small blue pt-4" style="background: rgb(222,220,11);background: linear-gradient(90deg, rgba(222,220,11,1) 0%, rgba(128,228,85,1) 50%, rgba(245,137,154,1) 100%);">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">AI JOBS</h5>
        <p>Some usefull links of our.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2021 Copyright:
    <a href="https://mdbootstrap.com/"> AIWORLD</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
{% endblock %}

frontend/templates/job/login.html
{% extends 'job/main.html' %}
{% block title %} Login {% endblock %}


{% block content%}

<style>
	body{
		background: rgb(222,220,11);
		background: linear-gradient(90deg, rgba(222,220,11,1) 0%, rgba(128,228,85,1) 50%, rgba(245,137,154,1) 100%);
	}
	.content {
  		background: rgb(0, 0, 0); /* Fallback color */
  		background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
  		bottom: 0;
  		color: #f1f1f1; /* Grey text */
  		width: 50%; /* Full width */
  		margin-top: 50px;
  		padding: 60px; /* Some padding */
  	}
</style>

<center>
<div class="content">
	<h1>Login</h1>
	<form>
		
	</form>

</div>
</center>
{% endblock %}

frontend/templates/job/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title> {% block title %}AI JOBS{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/main.css' %}">
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
    <script rel="stylesheet" type="text/css" src="{% static 'accounts/js/bootstrap.js' %}"></script>

</head>
<body>
    {% include 'job/navbar.html' %}
    
    {% block content %}
        
    {% endblock %}
    
</body>
</html>

frontend/templates/job/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ADFF2F">
  <a class="navbar-brand" href="#" style="font-size: 30px;">AI JOBS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="color: white">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'jobfrontend:home' %}" style="font-size: 20px">Home </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#" style="font-size: 20px">Jobs</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'jobfrontend:login' %}" style="font-size: 20px">Login</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#" style="font-size: 20px">Register</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>